### ISSUE TITLE
Firefox and other clients hang

### ISSUE THREAD

**Issue by pac85** [mahkoh/jay#317] opened 2024-11-04 16:18 UTC
I can reproduce it if I use the tabbed layout and launch Firefox twice: the second instance will be stuck and unresponsive.
Eventually the second instance might get stuck as well sometimes.
I know this is not much info but I'm not sure where to start debugging this, let me know if you have some ideas if you can't repro.

Once my terminal (Alacritty) got stuck as well but I found no way of reliably reproducing that.

**Comment by mahkoh** [comment] 2024-11-04 16:21
Please post the log file `jay log --path`.

**Comment by pac85** [comment] 2024-11-04 18:54
https://gist.github.com/pac85/86cdbeec900a0ca16ef63361b00ef716

**Comment by mahkoh** [comment] 2024-11-04 18:58
The logs look reasonable. Please post the when running an affected program with WAYLAND_DEBUG=1.

**Comment by pac85** [comment] 2024-11-05 12:34
In this gist there are two files, one is the first firefox instance that doesn't hang and the other is the second instance that does hang.

https://gist.github.com/pac85/65be96c469b72932252c60e65efa51f9

**Comment by mahkoh** [comment] 2024-11-05 12:44
What exactly do you mean by "hang"? It seems that the second instance isn't even creating a window.

**Comment by mahkoh** [comment] 2024-11-05 14:25
Could you record a video of this?

**Comment by pac85** [comment] 2024-11-05 14:58
https://github.com/user-attachments/assets/20bae96a-3238-4be4-ae9b-7532b0b62472

**Comment by mahkoh** [comment] 2024-11-05 15:36
I was finally able to reproduce by setting `gfx.swap-interval.egl = true` in firefox.

**Comment by pac85** [comment] 2024-11-05 15:49
Oh yeah it is true over here sorry for not mentioning it (forgot I even changed it).

**Comment by mahkoh** [comment] 2024-11-05 16:05
I believe this is just a firefox bug. It behaves the same in sway. I assume that firefox is blocked trying to acquire the next swapchain image for the first, now obscured, window.

**Comment by pac85** [comment] 2024-11-05 17:56
Ah ok, sorry I hope I haven't made you spend too much time on this.

**Comment by mahkoh** [comment] 2024-11-05 18:01
Don't worry about it. Closing this since I don't believe this is an issue in Jay. If you find a reproducer other than firefox, please comment.

**Closed by mahkoh** 2024-11-05 18:01 UTC
